module.exports = {
    BASE_URL: "http://26.35.61.52:3000",
    POST_PROFILE: "/api/account/profile",
    POST_LOGIN: "/api/account/login",
    POST_REGISTER: "/api/account/register",
    POST_UPDATE_PROFILE: "/api/account/updateProfile",
    POST_CHANGE_PASSWORD: "/api/account/changepassword",
    POST_CREATE_API: "/api/v1/create/api",
    POST_API: "/api/v1/getAllAPIByID",
    POST_FORGOT: "/api/account/forgotpassword",
    POST_UPLOAD_IMAGE: "/api/upload/uploadAvatar",
    POST_UPLOAD_IMAGE_POST: "/api/upload/uploadImagePost",
    URL_IMAGE: "https://api-server-game.herokuapp.com/images/",
    POST_MANANGER_API: "/api/v1/getAllApiById",
    POST_CREATE_POST: "/api/post/creatPost",
    GET_GET_ALL_POST: "/api/post/getAllPost",
    POST_DELETE_POST: "/api/post/deletePost",
    GET_POST_BY_ID: "/api/post/getPostByID",
    POST_UPDATE_POST: "/api/post/updatePost",
    POST_SEARCH_POST: "/api/post/findPost?keyword=",
    POST_UPLOAD_IMAGE_SUMMERNOTE: "/api/upload/uploadSummernote",
    POST_DETAIL_API: "/api/v1/getAPIbyID",
    POST_DELETE_API: "/api/v1/deleteAPI",
    ALLPOST_TUTORIAL: "/api/post/getAllPost",
    DETAIL_POST: "/api/post/getPostByID"
}